import { BASE_URL, PARTIAL_URL, REQUEST_METHODS, RESPONSE_STATUS } from './respReq';

export const APP_TITLE = 'ADMIN.BIKE-BOOKING.COM';

export { BASE_URL, PARTIAL_URL, REQUEST_METHODS, RESPONSE_STATUS };
